-- Passkeys (WebAuthn) storage for biometric login

create table if not exists public.passkey_credentials (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  credential_id text not null unique,
  public_key text not null,
  counter bigint not null default 0,
  transports text[] not null default '{}',
  device_name text,
  aaguid text,
  created_at timestamptz not null default now(),
  last_used_at timestamptz,
  revoked_at timestamptz
);

create index if not exists idx_passkey_credentials_user_id
  on public.passkey_credentials(user_id);

create index if not exists idx_passkey_credentials_active_user
  on public.passkey_credentials(user_id)
  where revoked_at is null;

alter table public.passkey_credentials enable row level security;

-- Owner-only policies (service role bypasses RLS by default)
drop policy if exists passkey_credentials_select_own on public.passkey_credentials;
create policy passkey_credentials_select_own
  on public.passkey_credentials
  for select
  to authenticated
  using (auth.uid() = user_id and revoked_at is null);

drop policy if exists passkey_credentials_insert_own on public.passkey_credentials;
create policy passkey_credentials_insert_own
  on public.passkey_credentials
  for insert
  to authenticated
  with check (auth.uid() = user_id);

drop policy if exists passkey_credentials_update_own on public.passkey_credentials;
create policy passkey_credentials_update_own
  on public.passkey_credentials
  for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists passkey_credentials_delete_own on public.passkey_credentials;
create policy passkey_credentials_delete_own
  on public.passkey_credentials
  for delete
  to authenticated
  using (auth.uid() = user_id);

revoke all on table public.passkey_credentials from anon;
revoke all on sequence public.passkey_credentials_id_seq from anon;

grant select, insert, update, delete on table public.passkey_credentials to authenticated;
grant usage, select on sequence public.passkey_credentials_id_seq to authenticated;
grant all on table public.passkey_credentials to service_role;
grant usage, select on sequence public.passkey_credentials_id_seq to service_role;
