-- Jornadas configurables por torneo (QA)
-- Permite definir "Fecha 1..N" con su fecha de inicio antes de crear partidos.

CREATE TABLE IF NOT EXISTS public.tournament_rounds (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tournament_id BIGINT NOT NULL,
  tenant_id UUID NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  round_number INTEGER NOT NULL CHECK (round_number > 0),
  round_name TEXT NOT NULL,
  start_at TIMESTAMPTZ NOT NULL,
  created_by UUID NULL REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT tournament_rounds_unique_tournament_round UNIQUE (tournament_id, round_number)
);

CREATE INDEX IF NOT EXISTS idx_tournament_rounds_tournament_round
  ON public.tournament_rounds (tournament_id, round_number);

CREATE INDEX IF NOT EXISTS idx_tournament_rounds_tenant_start
  ON public.tournament_rounds (tenant_id, start_at);

CREATE OR REPLACE FUNCTION public.set_tournament_rounds_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_tournament_rounds_updated_at ON public.tournament_rounds;

CREATE TRIGGER trg_tournament_rounds_updated_at
BEFORE UPDATE ON public.tournament_rounds
FOR EACH ROW
EXECUTE FUNCTION public.set_tournament_rounds_updated_at();

ALTER TABLE public.tournament_rounds ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  CREATE POLICY tournament_rounds_select_policy ON public.tournament_rounds
    FOR SELECT
    USING (
      EXISTS (
        SELECT 1
        FROM public.profiles p
        WHERE p.id = auth.uid()
          AND p.active = TRUE
          AND (
            p.role = 'super_admin'
            OR p.tenant_id = tournament_rounds.tenant_id
          )
      )
    );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE POLICY tournament_rounds_insert_policy ON public.tournament_rounds
    FOR INSERT
    WITH CHECK (
      EXISTS (
        SELECT 1
        FROM public.profiles p
        WHERE p.id = auth.uid()
          AND p.active = TRUE
          AND (
            p.role = 'super_admin'
            OR (p.role IN ('admin', 'manager') AND p.tenant_id = tournament_rounds.tenant_id)
          )
      )
    );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE POLICY tournament_rounds_update_policy ON public.tournament_rounds
    FOR UPDATE
    USING (
      EXISTS (
        SELECT 1
        FROM public.profiles p
        WHERE p.id = auth.uid()
          AND p.active = TRUE
          AND (
            p.role = 'super_admin'
            OR (p.role IN ('admin', 'manager') AND p.tenant_id = tournament_rounds.tenant_id)
          )
      )
    )
    WITH CHECK (
      EXISTS (
        SELECT 1
        FROM public.profiles p
        WHERE p.id = auth.uid()
          AND p.active = TRUE
          AND (
            p.role = 'super_admin'
            OR (p.role IN ('admin', 'manager') AND p.tenant_id = tournament_rounds.tenant_id)
          )
      )
    );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE POLICY tournament_rounds_delete_policy ON public.tournament_rounds
    FOR DELETE
    USING (
      EXISTS (
        SELECT 1
        FROM public.profiles p
        WHERE p.id = auth.uid()
          AND p.active = TRUE
          AND (
            p.role = 'super_admin'
            OR (p.role IN ('admin', 'manager') AND p.tenant_id = tournament_rounds.tenant_id)
          )
      )
    );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

GRANT SELECT, INSERT, UPDATE, DELETE ON public.tournament_rounds TO authenticated;
GRANT ALL ON public.tournament_rounds TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.tournament_rounds_id_seq TO authenticated, service_role;
